### ISSUE TITLE
if-then-elseif-else-endif

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#41]
As a coder, I can write multi-part conditionals using if-then-elseif-else-endif syntax. 

 * [x] Create branch v0.1/41_if_syntax
 * [x] Start [the wiki page](https://github.com/Spicery/Nutmeg/wiki/HOW-TO-Add-a-New-Language-Feature) that provides a walk through of adding a new language feature (output is a wiki page URL added to the side-bar)
 * [x] Start the page to Nutmeg in a Nutshell (/docs) explaining the syntax
 * [x] Update `tokenizer.py` to recognise the tokens `if`, `then`, `elseif`, `else`, `endif`
 * [x] Ensure that the vs-nutmeg-extension recognises the tokens (see above) (output is an update to the VS extension)
 * [x] Extend `parser.py` with a prefix mini-parser to recognise the multi-part conditional and translate it into the 3-part-if structure.
 * [x] Extend `resolver.py` to correctly handle the lexical-scopes of an if-then-else.
 * [x] Add the IfCodelet to the runner
 * [x] Submit pull request
 * [ ] Respond to any comments
 * [ ] Complete pull-requests (output is new functionality)
 * [x] Complete the wiki article (output is a wiki page, added to the sidebar)
 * [x] Complete the Nutshell page (output is a manual page)

# Acceptance Criteria

 * The `:` must be an alternative to `then`
 * `else` and `else:` must be allowed
 * `end` and `endif` must be valid alternatives
 * An if-statement must be acceptable without an `else` part
 * An if-statement may have zero or more `elseif` parts
 * The predicates of an if-statement must return a single boolean value or a typed error is raised
 * The action parts of if-statements must introduce new lexical scopes
 * Conditions are tested in order and when a condition returns true, the associated action is executed and then execution continues from after the `endif`, other conditions are ignored
 * If all conditions fail, the `else` part is executed if it exists

**Comment by philallen117** [comment]
What is the type of
```
if couldBeFalse then 1
```
Should there be a final `;;` on the `then` to make it return nothing same as the implicit `else` branch?
Actually, I have to get my head around this. `Nothing` is usually 'not coming back' (bottom). Whereas 'nothing to see here' could be Unit. So`;;` could be Any -> Unit.

**Comment by sfkleach** [comment]
> What is the type of
> 
> ```
> if couldBeFalse then 1
> ```
> 
> Should there be a final `;;` on the `then` to make it return nothing same as the implicit `else` branch?
> Actually, I have to get my head around this. `Nothing` is usually 'not coming back' (bottom). Whereas 'nothing to see here' could be Unit. So`;;` could be Any -> Unit.

Sounds about right. I would type this as `Int|Unit`, where `|` is type union.
